### ISSUE TITLE
Pwntools v5 - Breaking changes roadmap

### ISSUE THREAD

**Issue by peace-maker** [Gallopsled/pwntools#2495]
With Pwntools 5 we'd like to clean up the codebase and get rid of some legacy features like support for Python 2. This issue can be used to keep track of all the changes which were on hold until a major version bump.

- [x] Drop Python 2.7 support / Require Python 3.10 #2519
  - https://github.com/Gallopsled/pwntools/pull/2535
- [ ] Python 3.8+ type hints
- [ ] Add pyproject extras to make pwntools installs slim by default https://github.com/Gallopsled/pwntools/pull/2245
- [ ] Remove deprecated commandline tools https://github.com/Gallopsled/pwntools/issues/2361
- [ ] Possibly switch ELF class to [LIEF](https://github.com/lief-project/LIEF) to allow easier PE / machO support
- [ ] Proper Windows support
  - https://github.com/Gallopsled/pwntools/pull/2524
- [ ] Switch order of `keepends` and `drop` commands of `tube.recvline`? https://github.com/Gallopsled/pwntools/pull/2476
- [ ] Strip newline in `tube.recvline` family of functions by default

Please leave a comment for anything missing or concerns.

**Comment by tesuji** [comment]
Do you plan to start the v5 development on new branch or just on the master branch?
Do you need some help the above items?

**Comment by peace-maker** [comment]
We haven't talked about it much yet. Any help is appreciated! We use Discord for communication, so please join and we can make a plan.

https://discord.gg/96VA2zvjCB
