### ISSUE TITLE
Testing framework metabugs

### ISSUE THREAD

**Issue by Idolf** [Gallopsled/pwntools#285]
We have a lot of testing that needs fixing at some point in the future.

- [x] #104 Regression testing framework for shellcode
- [x] #189 Not all unit tests are run in 'make doctest'
- [x] #205 https://coveralls.io/ -- do we want it?
- [x] #211 Running doctest gives a bunch of warnings
- [ ] #260 Travis should check that all files in examples work
- [ ] #284 Travis should run all the examples in the pwntools-writeups repo
- [ ] #286 Do cycle detection as part of the Travis testing

Ideally we should also have some tests for the terminal (though it is pretty hard to do so). This seems like the component with the largest amount of bugs and the least amount of testing.

I think it would make sense to change the way we do testing. As @zachriggle mentioned in #189, it would probably make sense to move away from using Sphinx -- at least away from using it as our primary way of testing.

We should probably do something along the lines of:

- Create a tests directory
- Pull in pwntools-regression and pwntools-write-ups inside it. I think we agreed earlier that the first one should just have the code copied in, while the second one should be a submodule.
- Update the way doctests are run
- Write some scripts to run all tests we want.

**Comment by zachriggle** [comment]
Pytest is pretty flexible and could serve our purposes pretty well. It permits blacklisting certain tests (e.g. Don't run the SSH tests) and has doctest auto discovery that's not limited to the exported routines and classes.  This could address a few of the issues, and replace Sphinx.  

Zach Riggle
